server:
  port: 8083

spring:
  application:
    name: comment-service
  datasource:
    url: jdbc:mysql://localhost:3306/music?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true