server:
  port: 8084
  tomcat:
    max-swallow-size: 100MB
    connection-timeout: 120000

spring:
  application:
    name: tools-service
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8
          max-wait: -1ms
  cache:
    redis:
      time-to-live: 3600000
      cache-null-values: true


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    accessKeyId:
    accessKeySecret:
    bucketName: