server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: music-service
          uri: lb://music-service
          predicates:
            - Path=/songs/**, /songlist/**, /playlist/**
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/comment/**
        - id: tools-service
          uri: lb://tools-service
          predicates:
            - Path=/tools/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true